name: Image build and push

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Tag to apply to the image.'
        required: true

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ env.IMAGE_NAME }}:${{ env.INPUT_IMAGETAG }}
