name: Publish image for release

on:
  release:
    types: [published]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get image tag
      id: get_image_tag
      # Strip the 'refs/tags/' AND 'v' from the tag/release name.
      run: echo '::set-output name=IMAGE_TAG::${GITHUB_REF#refs/tags/v}'

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ env.IMAGE_NAME }}:${{ steps.get_image_tag.outputs.IMAGE_TAG }}
