name: Image build and push

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the image
      run: docker build . --file Dockerfile --tag ghcr.io/blachniet/kustomize-plugins:latest

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push the image
      run: docker push ghcr.io/blachniet/kustomize-plugins:latest
